Lesson eight mature
DADUSHKA/web_application pull request #10
Opened 2018-11-11 10:04 UTC by DADUSHKA

2018-11-11 12:46 UTC, BubuntuClu requested changes

2018-11-11 12:46 UTC, BubuntuClu commented on app/models/question.rb
> +  scope :by_test, ->(test_name) do
это что такое? у тебя есть `belongs_to :test`. с другими тестами у тебя не может быть связи

2018-11-11 12:46 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :question_head, ->(value) { find(value) }
что такое `value`?

2018-11-11 12:46 UTC, BubuntuClu commented on app/models/user.rb
> +  scope :user_on_test, ->(test_title) { find(test_title) }
что-то я не понимаю смысла всех твоих новый скоупов. у тебя ведь ассоциации.

2018-11-11 12:46 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +    Question.by_test(test_title).each do |resource|
`test.questions`

2018-11-11 12:46 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +    Test.question_head(value)
`question.test.title`?

2018-11-11 12:46 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +    Category.category_on_test(value.category_id).title
это тоже все можно по ассоциации достать

2018-11-11 12:46 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +    User.user_on_test(value.author_id).name
это тоже все можно по ассоциации достать

2018-11-11 12:47 UTC, BubuntuClu commented
это не увидел "Список вопросов теста должен выводиться на той же странице, что и сам тест"
так же нет хелпера для вопросов, который будет возвращать текст создания/редактирования

2018-11-12 07:44 UTC, DADUSHKA commented on app/helpers/tests_helper.rb
> +    Category.category_on_test(value.category_id).title
ok

2018-11-12 07:45 UTC, DADUSHKA commented on app/helpers/tests_helper.rb
> +    User.user_on_test(value.author_id).name
ok

2018-11-12 07:51 UTC, DADUSHKA commented on app/models/test.rb
> +  scope :question_head, ->(value) { find(value) }
ok

2018-11-12 07:52 UTC, DADUSHKA commented on app/models/question.rb
> +  scope :by_test, ->(test_name) do
ok

2018-11-12 07:52 UTC, DADUSHKA commented on app/models/user.rb
> +  scope :user_on_test, ->(test_title) { find(test_title) }
ok

2018-11-12 07:52 UTC, DADUSHKA commented on app/helpers/tests_helper.rb
> +    Question.by_test(test_title).each do |resource|
ok

2018-11-12 17:26 UTC, BubuntuClu commented on app/views/tests/show.html.erb
> +      <strong>Total questions:</strong>
наименование, конечно, намекает на количество вопросов

2018-11-12 17:26 UTC, BubuntuClu commented on app/views/tests/show.html.erb
> +      <%= total_questions %>
тут можно паршиал использовать. выводить не просто через запятую, а как ссылку каждый вопрос

2018-11-12 17:26 UTC, BubuntuClu commented on app/views/tests/show.html.erb
> +      <%= total_questions %>
так же я бы явно передал параметр `@test` в метод, чтоб было понятно что за тест берется в хелпере

2018-11-12 17:26 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +    Test.question_header(instance_id).title
я имел в виду, что этот хелпер не нужен.
там где ты его используешь сейчас, ты можешь вместо `question_header(@question.test_id)` написать `question.test.title`
у тебя вопрос принадлежит к одному только тесту. по ассоциации ты можешь его достать

2018-11-12 17:26 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :by_level, ->(namber) { where(level: namber) }
`number`

2018-11-12 19:59 UTC, DADUSHKA commented on app/helpers/tests_helper.rb
> +    Test.question_head(value)
ok

2018-11-12 20:03 UTC, DADUSHKA commented on app/helpers/tests_helper.rb
> +    Test.question_head(value)
А как, сдесь questina ещё нет?

2018-11-12 20:03 UTC, DADUSHKA commented on app/views/tests/show.html.erb
> +      <strong>Total questions:</strong>
ok

2018-11-12 20:03 UTC, DADUSHKA commented on app/views/tests/show.html.erb
> +      <%= total_questions %>
ok

2018-11-12 20:04 UTC, DADUSHKA commented on app/views/tests/show.html.erb
> +      <%= total_questions %>
ok

2018-11-12 20:04 UTC, DADUSHKA commented on app/helpers/tests_helper.rb
> +    Test.question_header(instance_id).title
ok

2018-11-12 20:06 UTC, DADUSHKA commented on app/models/test.rb
> +  scope :by_level, ->(namber) { where(level: namber) }
ok

2018-11-12 20:26 UTC, DADUSHKA commented on app/helpers/tests_helper.rb
> +    Test.question_head(value)
Я имел ввиду new.question

2018-11-13 00:24 UTC, psylone requested changes

2018-11-13 00:24 UTC, psylone commented on app/helpers/application_helper.rb
> +    link_to title, repo
В новой вкладке ссылку на другой ресурс открывать следует.

2018-11-13 00:24 UTC, psylone commented on app/helpers/application_helper.rb
> +    Time.zone.now.year
```suggestion
    Time.current.year
```

2018-11-13 00:24 UTC, psylone commented on app/helpers/tests_helper.rb
> +  def question_header(instance)
Почему `question_header` хэлпер находится в `TestsHelper`, а не `QuestionsHelper`?

2018-11-13 00:24 UTC, psylone commented on app/helpers/tests_helper.rb
> +  def all_test_questions(instance)
Не нужно называть параметр `instance`, это хэлпер тестов поэтому лучше `test` как выше в методе `level_test`.

2018-11-13 00:24 UTC, psylone commented on app/helpers/tests_helper.rb
> +    instance.questions.each do |resource|
```suggestion
    instance.questions.pluck(:description)
```

2018-11-13 00:24 UTC, psylone commented on app/helpers/tests_helper.rb
> +    var
Намудрил.

2018-11-13 00:24 UTC, psylone commented on app/views/layouts/application.html.erb
> +      <div id="footer">
Помести весь футер во фрагменте, чтобы здесь был только вызов `<%= render "shared/footer" %>`.

2018-11-13 00:24 UTC, psylone commented on app/views/layouts/application.html.erb
> +        &copy; Учебный проект в онлайншколе <a href="http://www.thinknetica.com/" target="_blank">    Thinknetica</a> | <%= output_current_year %>
Используй `link_to`.

2018-11-13 00:24 UTC, psylone commented on app/views/layouts/application.html.erb
> +        <%= render "shared/footer", layout: false %>
Зачем `layout: false`?

2018-11-13 00:24 UTC, psylone commented on app/views/questions/index.html.erb
> -<h1>Questions</h1>
Этого шаблона не должно быть, поскольку список вопросов рендерится на странице просмотра теста.

2018-11-13 00:24 UTC, psylone commented on app/views/questions/new.html.erb
> +  <h2>Create New <%= question_header(@test) %> Question</h2>
Сделай так чтобы здесь был только вызов: `<h2><%= question_header(@question) %></h2>`.

2018-11-13 00:24 UTC, psylone commented on app/views/questions/new.html.erb
> +  <h2>Create New <%= question_header(@test) %> Question</h2>
Передавай объект вопроса вместо теста, мы же заголовок формы вопроса определяем.

2018-11-13 00:24 UTC, psylone commented on app/views/shared/_footer.html.erb
> +      <%= github_url("TestGuru", "https://github.com/DADUSHKA/web_application.git") %> это:
Сделай передачу 3-х параметров: `github_url('TestGuru', 'DADUSHKA', 'web_application')`.

2018-11-13 00:24 UTC, psylone commented on app/views/tests/show.html.erb
> +      <%= render 'all_test_questions', test: @test %>
Здесь нужно рендерить шаблон `questions/question` для каждого объекта из коллекции `@test.questions`.

2018-11-13 00:24 UTC, psylone commented on app/models/test.rb
> +  scope :question_header, ->(instance_id) { find(instance_id) }
Скоуп должен возвращать релейшен.

2018-11-13 00:24 UTC, psylone commented on app/helpers/tests_helper.rb
> +    Test.question_header(instance.id).title
Принимай в параметре объект вопроса и на основе того сохранен ли он в базе данных (есть соответствующий метод) выводи нужный текст.

2018-11-29 10:49 UTC, psylone requested changes

2018-11-29 10:49 UTC, psylone commented on app/controllers/questions_controller.rb
Метод `index` больше не нужен.

2018-11-29 10:49 UTC, psylone commented on app/controllers/questions_controller.rb
> -
Здесь тоже необходимо рендерить шаблон, вместо `inline`.

2018-11-29 10:49 UTC, psylone commented on app/helpers/application_helper.rb
> +    link_to title, "https://github.com/" + login + "/" + repo, target: :_blank
```suggestion
    link_to title, "https://github.com/#{login}/#{repo}", target: :_blank
```

2018-11-29 10:49 UTC, psylone commented on app/models/test.rb
> +  scope :question_header, ->(instance_id) { find(instance_id) }
`find` возвращает конкретный объект, а не объект `ActiveRecord::Relation`. Кроме того, нет смысла оборачивать в скоуп метод `find`, это не привносит ничего нового.

2018-11-29 10:49 UTC, psylone commented on app/helpers/questions_helper.rb
> +  def question_header(instance)
Даже если у тебя нет записи в базе данных, объект все равно создается в памяти. Например: `Question.new` разместит в памяти новый объект класса `Question`, хотя в базе его ещё нет.

2018-11-29 10:49 UTC, psylone commented on app/helpers/questions_helper.rb
> +  def question_header(instance)
В зависимости от того был ли объект сохранен в базе или нет тебе необходимо формировать правильный заголовок. Скоуп и модель `Test` для этого использовать не нужно.

2018-11-29 10:49 UTC, psylone commented on app/views/questions/new.html.erb
> +  <h2>Create New <%= question_header(@test) %> Question</h2>
При текущей реализации смысла от хэлпера нет. Он должен возвращать всю строку заголовка и вызываться как в комментарии выше.

2018-11-29 10:49 UTC, psylone commented on app/views/layouts/application.html.erb
> +      <div id="footer">
❓

2018-11-29 20:42 UTC, BubuntuClu requested changes

2018-11-29 20:42 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    if @test.update!(test_params)
бэнг метод не надо вызывать. если у тебя не пройдет апдейт, он не уйдет в ветку false, он выбросит исключение, а его ты тут не ловишь

2018-11-29 20:42 UTC, BubuntuClu commented on app/views/layouts/application.html.erb
> +        &copy; Учебный проект в онлайншколе <%= thinknetica_url %> | <%= output_current_year %>
это в футере надо отображать

2018-11-29 20:42 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +  <h2>Create New <%= question_header(@test) %> Question</h2>
не исправлено? может ты не запушил изменения?

2018-11-29 20:42 UTC, BubuntuClu commented on app/views/tests/show.html.erb
> +      <strong>Authir:</strong>
очепячтка

2018-11-29 20:42 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +  # def all_test_questions(test)
комментарии сразу удаляй

2018-11-29 20:42 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def question_header(instance)
это не исправлено? надо сюда передавать объект вопроса и проверять есть ли он в БД или нет. в зависимости от этого выводить ту или иную фразу

2018-12-01 09:16 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def question_header(instance)
не совсем так. у тебя здесь должна возвращаться фраза "Create New..." или "Edit..."
и этот хелпер ты просто вызываешь во view new и edit.
`<h2>Create New <%= question_header(@question) %> Question</h2>` вот эта строка у тебя уйдет, вместо нее будет просто вызов хелпера

2018-12-01 09:16 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +    <h2>Editing  <%= @question.test.title %> Question</h2>
тут должен быть вызов хелпера

2018-12-01 09:16 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +      Test.find(@test.id).title
доставай тест по ассоциации из переданного вопроса

2018-12-01 13:22 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    if @test.update!(test_params)
это поправить надо

2018-12-02 12:08 UTC, psylone approved these changes

2018-12-02 12:08 UTC, psylone commented on app/controllers/questions_controller.rb
>    def new
```ruby
@question = @test.questions.new
```

Лучше так чтобы у созданного в памяти объекта вопроса сразу проставился идентификатор связанного теста в атрибуте `test_id`.

2018-12-02 12:08 UTC, psylone commented on app/helpers/application_helper.rb
> +  def output_current_year
Лучше назвать просто `current_year`, поскольку по факту метод лишь возвращает значение и ничего не выводит.

2018-12-02 12:08 UTC, psylone commented on app/views/layouts/application.html.erb
> +      <div id="footer">
Молодец! Ещё бы `<div id="footer">` тоже поместить внутри самого фрагмента футера )

2018-12-02 12:08 UTC, psylone commented on app/views/questions/edit.html.erb
> +    <h2><%= question_header(@question) %></h2>
👍

2018-12-02 16:12 UTC, merged