Lesson nine two
DADUSHKA/web_application pull request #11
Opened 2018-12-19 15:35 UTC by DADUSHKA

2018-12-19 16:17 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +  before_action :find_question, only: %i[new create]
используй один нейминг для методов. у тебя одна логическая операция выполняется, поиск объекта, а методы ты называешь через `set_*` и `find_*`

2018-12-19 16:17 UTC, BubuntuClu commented on app/models/test.rb
> +                    .order(created_at: :desc)
в скоупе не должно быть сортировки.

2018-12-19 16:17 UTC, BubuntuClu commented on app/views/test_passages/show.html.erb
> +
много отступов

2018-12-19 16:17 UTC, BubuntuClu commented on app/views/test_passages/show.html.erb
> +<%=   %>
?

2018-12-19 16:17 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +module TestPassagesHelper
как-то все очень сложно ты сделал.

можно в моделе `test_passage` сделать метод, который будет возвращать успешно или нет пройден тест.
в нем же определенить константу для числа "85", иначе не понятно что это за число такое
и во вьюхе просто сделать 
```
if test_passage.succes?
   success message
else
  unseccess message
```

2018-12-20 17:42 UTC, psylone requested changes

2018-12-20 17:42 UTC, psylone commented on app/models/test_passage.rb
> +    question_namber - 1
В таком обратном вызове нет особого смысла, поскольку мы присваиваем **локальной** переменной некоторое значение, а затем вычитаем единицу. При этом результат нигде не сохраняется.

2018-12-20 17:42 UTC, psylone commented on app/models/test_passage.rb
> +  before_update :before_update_next_question
Оба обратных вызова по сути отвечают за одну задачу: установить следующий вопрос, поэтому их стоит объединить в единый обратный вызов.

2018-12-20 17:42 UTC, psylone commented on app/models/test_passage.rb
> +    question.id - before_validation_number_question
Не стоит использовать обратный вызов внутри обычных методов.

2018-12-20 17:42 UTC, psylone commented on app/models/test_passage.rb
> +    question.id - before_validation_number_question
Нет гарантии что идентификаторы вопросов одного теста будут идти подряд один за другим.

2018-12-20 17:42 UTC, psylone commented on app/models/test_passage.rb
> +    question.id - before_validation_number_question
Также, я бы изменил название метода, например: `question_number`, поскольку по сути это номер текущего вопроса.

2018-12-20 17:42 UTC, psylone commented on app/views/test_passages/result.html.erb
> +  <h2><%= selection_message(@test_passage.test, @test_passage.correct_questions) %> </h2>
Нет смысла передавать 2 аргумента, можно внутри метода у объекта `@test_passage` получить все что нужно.

2018-12-20 17:42 UTC, psylone commented on app/views/test_passages/result.html.erb
> +<%= success_rate(@test_passage.test, @test_passage.correct_questions) %>%
Поскольку процент правильных ответов это данные, логично сделать метод модели для этого.

2018-12-20 17:42 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +  def success_rate(object_1, object_2)
Не стоит именовать параметры `object_1`, совсем не понятно что это за объект. Лучше сделать `success_rate(test, correct_questions)`. Хотя на самом деле здесь достаточно получить в параметре единственный объект `test_passage`.

2018-12-20 17:42 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +  end
Постарайся переписать эти хэлперы отталкиваясь от идеи что хэлперы отвечают больше за логику отображения данных, тогда как сами данные относятся к модели и должны быть определены в методах модели.

Например, у модели может быть метод `test_passage.success_rate`, а хэлпер может использовать этот метод чтобы сформировать необходимый текст или HTML для вывода в шаблоне.

2018-12-20 18:40 UTC, DADUSHKA commented on app/models/test_passage.rb
> +  before_update :before_update_next_question
ok

2018-12-21 11:05 UTC, psylone requested changes

2018-12-21 11:05 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +  def selection(str_1, str_2)
Стоит сделать этот метод приватным.

2018-12-21 11:05 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +  def selection_message
`selection_message` звучит не вполне ясно, по факту это сообщение о результате прохождения теста, можно назвать, например: `result_message`.

2018-12-21 11:05 UTC, psylone commented on app/models/test_passage.rb
> +    @@user_count_answers_correct += answer_ids.count if answer_ids.present?
Мы увеличиваем счетчик верных ответов, хотя на данном этапе ещё не факт что в `answer_ids` все идентификаторы принадлежат к верным ответам.

2018-12-21 11:05 UTC, psylone commented on app/models/test_passage.rb
> +  @@user_count_answers_correct = 0
Переменная класса в этом задании точно не нужна.

2018-12-21 11:05 UTC, psylone commented on app/models/test_passage.rb
> +      all_count_answers_correct += i.answers.correct.count
Такие вещи нужно делать с помощью скоуп методов.

2018-12-21 11:05 UTC, psylone commented on app/models/test_passage.rb
> +    ((100.0 / all_count_answers_correct) * @@user_count_answers_correct).to_i
Не уверен что нам нужно хранить информацию о верных ответах. Достаточно информации о количестве правильно отвеченных вопросов. Тогда зная общее количество вопросов мы сможем посчитать `success_rate`.

2018-12-21 11:05 UTC, psylone commented on app/models/test_passage.rb
> +  @@user_count_answers_correct = 0
Имей в виду что переменная класса хранит значение для всего дерева наследования классов. Это значит что у любого дочернего/родительского класса значение переменной класса будет одним и тем же (потому что физически в памяти это одна и та же область). А также, для всех объектов переменная класса фактически будет хранить одно и то же значение, а это скорее всего не то что нам нужно.

2018-12-21 22:43 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
>      selection("The  #{@test_passage.test.title} Test was Completed.",
зачем тебе функция, которая просто вызывает другую функцию? сразу тут и делай `if`

2018-12-21 22:43 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    if @test_passage.success_rate >= 85
`85` надо поместить в константу. не понятно что за 85 такое.

2018-12-21 22:43 UTC, BubuntuClu commented on app/views/test_passages/show.html.erb
> +    <%=   %>
это что-то лишнее осталось

2018-12-22 23:21 UTC, psylone requested changes

2018-12-22 23:21 UTC, psylone commented on app/helpers/test_passages_helper.rb
>    def selection(str_1, str_2)
На самом деле, нет ничего страшного, если у тебя в обоих методах будет повторяться условное выражение. Это будет более понятно, чем например вызов `selection('green', 'red')`.

2018-12-22 23:21 UTC, psylone commented on app/helpers/test_passages_helper.rb
>      selection("The  #{@test_passage.test.title} Test was Completed.",
Также здесь лучше передавать объект `test_passage` в параметре, чтобы сделать код менее связанным.

2018-12-22 23:21 UTC, psylone commented on app/models/question.rb
> +  scope :answers_correct, -> { includes(:answers).where(answers: { correct: true }) }
Этот скоуп избыточен, ты можешь сделать `question.answers.correct`.

2018-12-22 23:21 UTC, psylone commented on app/models/test_passage.rb
> +  belongs_to :question, class_name: 'Question', optional: true
Поскольку ассоциация называется `question`, можно не указывать `class_name`.

2018-12-22 23:21 UTC, psylone commented on app/models/test_passage.rb
> +  before_validation :before_validation_set_and_next_question
```suggestion
  before_validation :before_validation_set_next_question
```

2018-12-23 09:43 UTC, BubuntuClu commented on app/models/question.rb
> +  scope :column_id, -> { select(:id) }
это плохой скоуп. он тебе возвращает урезанные данные об объекте, его нельзя поставить в цепочку вызовов

2018-12-25 07:43 UTC, psylone approved these changes

2018-12-25 07:43 UTC, psylone commented on app/models/question.rb
> +  scope :column_id, -> { select(:id) }
На самом деле, `select` возвращает объект класса `ActiveRecord::Relation`, так что в цепочку поставить можно.

2018-12-25 07:43 UTC, psylone commented on app/models/question.rb
> +  scope :column_id, -> { select(:id) }
А вот сам скоуп здесь в принципе избыточен. Будет лучше в самом выражении использовать `select`.

2018-12-25 07:43 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +    if test_passage.success_rate >= TEST_THRESHOLD
Можно также в модели определить метод `test_passage.success?`

2018-12-25 07:43 UTC, psylone commented on app/models/test_passage.rb
> +    test_passage.test.questions.column_id.index(self.question) + 1
Поскольку СУБД возвращает по умолчанию записи в произвольном порядке, необходимо также делать сортировку по `id` с помощью метода `order` из ActiveRecord.

2018-12-26 08:08 UTC, merged