Lesson fourteen
DADUSHKA/web_application pull request #16
Opened 2019-01-23 20:32 UTC by DADUSHKA

2019-01-23 21:30 UTC, BubuntuClu requested changes

2019-01-23 21:30 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
>      if @test.save
```
@test = current_user.author_tests.new(test_params)
if @test.save...
```

2019-01-23 21:30 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +      flash[:notice] = "Welcome back, #{current_user.first_name}!"
ты создаешь тест, почему сообщение говорит о "возвращении назад"?)

2019-01-23 21:30 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +      flash[:notice] = "Welcome back, #{current_user.first_name}!"
ты апдейтишь тест, почему сообщение говорит о "возвращении назад"?)

2019-01-23 21:30 UTC, BubuntuClu commented on app/models/gist.rb
> + scope :gists, -> { all }
какой смысл в этом скоупе?

2019-01-23 21:30 UTC, BubuntuClu commented on app/models/user.rb
> +  scope :by_id, ->(user_id) { find(user_id) }
`User.by_id(id)` `User.find(id)`? в чем разница? количество символов одинаковое, но чтоб сделать "_" надо еще шифт нажать)
ты же в скоупе используешь просто метод AR. в чем смысл?

2019-01-23 21:30 UTC, BubuntuClu commented on config/application.rb
> +    config.autoload_paths << "#{Rails.root}/lib/clients"
это уже не нужно

2019-01-23 21:30 UTC, BubuntuClu commented on db/migrate/20190122120820_create_gists.rb
> +        t.string   :question
сделай через привязку к вопросу. `t.references`

2019-01-23 21:30 UTC, BubuntuClu commented on app/models/question.rb
> +  scope :object, ->(title) { find_by(description: title) }
совершенно не говорящее имя скоупа. что за `object`? и скоуп должен возвращать `ActiveRecord::Relation`, для того чтобы можно было делать цепочку вызовов.

2019-01-23 21:30 UTC, BubuntuClu commented on app/models/question.rb
> +  scope :object, ->(title) { find_by(description: title) }
так же не вижу зачем нужен такой скоуп

2019-01-23 21:30 UTC, BubuntuClu commented on app/models/user.rb
> +  scope :by_id, ->(user_id) { find(user_id) }
тоже самое на счет цепочки вызовов

2019-01-23 21:30 UTC, BubuntuClu commented on app/views/admin/tests/_gist.html.erb
> +    <td><%= User.by_id(data.user_id).email %></td>
у тебя ведь есть ассоциация с пользователем, который гист создал. `data.user`

2019-01-23 21:30 UTC, BubuntuClu commented on app/views/admin/tests/_gist.html.erb
> +    <td><%= link_to data.question, admin_question_path(Question.object(data.question)) %></td>
сделай связку с вопросом через id и не будет проблем с вызовом пути

2019-01-23 21:30 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      Gist.new.entry_in_the_table(@test_passage.question.description,
`current_user.gists.create( question, url)`

2019-01-23 21:30 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      Gist.new.entry_in_the_table(@test_passage.question.description,
и ты создаешь запись, до проверки успешно ли у тебя прошло создание, не надо так

2019-01-23 21:30 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    @client = client || Octokit::Client.new(access_token: @token.to_s)
у тебя ведь токен в файле лежит, бери его оттуда через `ENV`

2019-01-23 21:30 UTC, BubuntuClu commented on db/migrate/20190122115857_add_token_to_users.rb
> +    t.string :token
не понял что за токен

2019-01-24 11:26 UTC, psylone requested changes

2019-01-24 11:26 UTC, psylone commented on app/services/gist_question_service.rb
> +      description: "A question about #{@test.title} from TestGuru!",
Вот это необходимо вынести в I18n.

2019-01-24 11:26 UTC, psylone commented on app/models/gist.rb
> +  def entry_in_the_table(question_id, gist_url, user_id)
Этот метод крайне не понятен, используй стандартные средства ActiveRecord.

2019-01-24 11:26 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +      flash[:notice] = if result.success?
Точно ли есть метод `success?` у результата который возвращает метод `call`?

2019-01-24 11:26 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +                                   current_user.id)
`current_user.gists.new()`.

2019-01-24 11:26 UTC, psylone commented on app/models/user.rb
> +  has_many :gist, dependent: :destroy
```suggestion
  has_many :gists, dependent: :destroy
```

2019-01-24 11:26 UTC, psylone commented on app/models/question.rb
> +  has_many :gist
```suggestion
  has_many :gists
```

2019-01-24 11:26 UTC, psylone commented on app/views/admin/tests/_gist.html.erb
> +<% Gist.all.each do|data| %>
У тебя во фрагменте должен рендерится конкретный гист, а не вся коллекция.

2019-01-24 11:26 UTC, psylone commented on app/views/admin/tests/index.html.erb
> +              <%= render 'gist' %>
Здесь нужно рендерить коллекцию как обычно.

2019-01-24 11:26 UTC, psylone commented on app/views/admin/tests/_gist.html.erb
> +    <td><%= link_to data.question.description, admin_question_path(data.question) %></td>
> Вопрос. Отображаются первые 25 символов тела вопроса в виде ссылки. По клике на ссылку отображается страница вопроса (действие show)

2019-01-24 11:26 UTC, psylone commented on app/views/admin/tests/index.html.erb
> +              <%= render 'gist' %>
Сделай отдельный контроллер для администратора который будет показывать список гистов.

2019-01-25 12:02 UTC, DADUSHKA commented on app/controllers/test_passages_controller.rb
> +      flash[:notice] = if result.success?
success? взят из видео к уроку

2019-01-25 12:17 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +      flash[:notice] = if result.success?
В видео не использовался Octokit.

2019-01-25 14:21 UTC, DADUSHKA commented on app/controllers/test_passages_controller.rb
> +      flash[:notice] = if result.success?
.empty?

2019-01-25 19:23 UTC, psylone approved these changes

2019-01-25 19:23 UTC, psylone commented on app/views/admin/gists/index.html.erb
> +           <% @gists.each do |data| %>
`render @gists`.

2019-01-25 19:23 UTC, psylone commented on config/routes.rb
> +   get 'gists/index'
`resources :gists, only: [:index]`.

2019-01-27 09:15 UTC, merged