Badge and timer
DADUSHKA/web_application pull request #21
Opened 2019-02-20 10:20 UTC by DADUSHKA

2019-02-20 20:12 UTC, BubuntuClu requested changes

2019-02-20 20:12 UTC, BubuntuClu commented on app/controllers/trophies_controller.rb
> +    @trophies = current_user.trophies
так же пользователь должен видеть список всех возможных трофеев

2019-02-20 20:12 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      # @test_passage.results_of_the_trophies(current_user.test_passages)
вот здесь это как раз было бы хорошо делать, а не во вьюхе

2019-02-20 20:12 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +
это не задача хелпера раздавать награды, это должен делать какой-нибудь сервис/класс.
хелпер нужен для упращения отображения чего-либо

2019-02-20 20:12 UTC, BubuntuClu commented on app/helpers/trophies_helper.rb
> +module TrophiesHelper
тоже самое про хэлпер

2019-02-20 20:12 UTC, BubuntuClu commented on app/views/trophies/index.html.erb
> +        <table class="table table-striped table-sm">
если добавиться новый вид наград, то надо будет верстку еще править? как-то это не хорошо

2019-02-20 20:12 UTC, BubuntuClu commented on app/views/test_passages/show.html.erb
> +  <span id="year">
что это такое, я вообще не понял. почему сразу нельзя вывести в нужном формате?

2019-02-20 20:12 UTC, BubuntuClu commented on app/assets/javascripts/utilites/timer.js
> +function time() {
а если `js` на странице отключат? можно будет сидеть сколько угодно. надо делать проверку на время на бэкэнде

2019-02-21 19:25 UTC, DADUSHKA commented on app/views/test_passages/show.html.erb
> +  <span id="year">
не нашел другого решения как передать числовые данные в newData()

2019-02-21 19:31 UTC, DADUSHKA commented on app/views/test_passages/show.html.erb
> +  <span id="year">
при created_at.strftime('%Y, %m, %d, %k, %M, %S') -таймер уходит в NaN

2019-02-22 06:27 UTC, BubuntuClu commented on app/controllers/trophies_controller.rb
> +    @trophies = Trophy.all
трофеи пользователя тоже показывать надо. тут два списка

2019-02-22 06:29 UTC, BubuntuClu commented on app/views/test_passages/show.html.erb
> +  <span id="year">
ты можешь просто в секундах вернуть число, на фронт преобразовать, допустим к минутам, и в таймере по секунде вычитать.

2019-02-22 06:30 UTC, BubuntuClu commented on app/assets/javascripts/utilites/timer.js
> +function time() {
обработки на бэкенде не вижу. надо оставшееся время проверять на бэкенде

2019-02-22 06:46 UTC, DADUSHKA commented on app/controllers/trophies_controller.rb
> +    @trophies = Trophy.all
пользователь видит список всех наград, с надписью, не заслужил, если ее нет у пользователя , а если есть , выводится колличество

2019-02-22 07:08 UTC, DADUSHKA commented on app/assets/javascripts/utilites/timer.js
> +function time() {
я не пойму, какое время надо проверять, я передаю в js время начала прохождения теста из test_passage, добавляю к нему в секундах время прохождения теста и таймер отсчитывает его, чтобы при обновлении страницы таймер не возвращался к началу время берется текущее, а не сохраняется в localStorage(реализация таймера с localStorage у меня получилось сделать только поминутно), а если js отключат, то тест можно пройти свободно, просто пользователя не выкинет на страницу result, если он задержится  с прохождением

2019-02-22 08:28 UTC, BubuntuClu commented on app/assets/javascripts/utilites/timer.js
> +function time() {
"а если js отключат, то тест можно пройти свободно", это ведь не хорошо. сделай проверку при апдейте, когда ты ищешь следующий вопрос, на время теста. если время вышло то перекидывай сразу на результат с сообщением что время вышло

2019-02-22 08:29 UTC, BubuntuClu commented on app/assets/javascripts/utilites/timer.js
> +function time() {
а на фронте ты просто время которое тебе возвращается, по секундно уменьшаешь, если на этой странице долго находиться то их перекидываешь через js на страницу результатов

2019-02-22 08:29 UTC, BubuntuClu commented on app/controllers/trophies_controller.rb
> +    @trophies = Trophy.all
👍

2019-02-22 10:17 UTC, psylone requested changes

2019-02-22 10:17 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +end
Отступы съехали.

2019-02-22 10:17 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +   @trophies_issued = DistributionTrophies.new(@test_passage, current_user.test_passages)
Пользователя мы можем взять у объекта `@test_passage`.

2019-02-22 10:17 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +    trophies_issued.successful_completion_tests_from_category(trophies)
Сколько же запросов к базе будет, учитывая сколько раз вызываются эти методы в шаблонах?

2019-02-22 10:17 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +    trophies_issued.successful_completion_tests_from_category(trophies)
Идея хорошая, но её стоит реализовать иначе. Например, выбрать 2 коллекции бэйджей: все и те которые есть у пользователя. Можно сделать `GROUP BY`. Тогда в шаблонах для каждого бэйджа из коллекции всех бэйджей будет достаточно проверить есть ли этот бэйдж в коллекции заработанных бэйджей пользователем.

2019-02-22 10:17 UTC, psylone commented on app/views/test_passages/result.html.erb
> +                                 trophy_speed(@trophies_issued, @trophies).present? %>
Не стоит в шаблоне изменять данные.

2019-02-22 10:17 UTC, psylone commented on app/models/test_passage.rb
> +  end
Можно конечно и в модели это оставить, хотя основная обязанность модели - это работа с данными, но не с бизнес логикой. Таким образом, стоит определить эти методы в сервисе.

2019-02-22 10:17 UTC, psylone commented on app/models/test_passage.rb
> +    if !question_id.nil?
Используй `unless`.

2019-02-22 10:17 UTC, psylone commented on app/services/distribution_trophies.rb
> +     @test_passage.success_rate >= TEST_THRESHOLD
Вот это можно сделать отдельным методом в `@test_passage`, например: `@test_passage.success?`.

2019-02-22 10:17 UTC, psylone commented on app/services/distribution_trophies.rb
> +    @current_user_test_passages = current_user_test_passages
Лучше просто `user_test_passages`, и так ясно что это текущий пользователь.

2019-02-22 10:17 UTC, psylone commented on app/services/distribution_trophies.rb
> +
При добавлении нового правила бэйджа придётся изменять код во множестве мест. В хорошем случае для этого необходимо добавить лишь один метод обработки логики выдачи бэйджа в данный сервис.

Общая логика выдачи бэйджей может быть примерно такой:

```ruby
def call
  badges = []

  Badge.all do |badge|
    badges.push(badge) if send("#{badge.rule}_passed?", badge.rule_value)
  end
end

private

def first_tests_from_category_passed?(category)
end
```

В `rule_value` предполагается хранение параметра для правила. Например, название категории за которую выдаются бэйджи.

2019-02-22 10:17 UTC, psylone commented on app/views/admin/tests/index.html.erb
>            <nav class="navbar navbar-light">
Навигацию стоит вынести в отдельный фрагмент.

2019-02-22 10:17 UTC, psylone commented on app/views/test_passages/result.html.erb
> +                                 trophy_speed(@trophies_issued, @trophies).present? %>
Не стоит изменять данные в шаблоне. Кроме того, при добавлении нового типа правила бэйджа придётся изменять ещё и код в шаблоне. В хорошем варианте для этого будет необходимо лишь добавить единственный метод обработки логики выдачи бэйджа в сервис.

2019-02-22 17:04 UTC, BubuntuClu commented
ты на проверку отправил только одно маленькое изменение? может не запушилось у тебя что-то? Евгений много комментариев тебе оставил.

2019-02-22 22:00 UTC, psylone requested changes

2019-02-22 22:00 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +  if @test_passage.created_at.to_time.to_i + @test_passage.test.time_test.to_i < Time.now.to_i
Стоит сделать метод модели, например: `@test_passage.timeout?`, а также предусмотреть случай если тест не содержит таймера.

2019-02-24 17:53 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +   @trophies_issued = DistributionTrophies.new(@test_passage, @test_passage.user, current_user.test_passages)
я думаю, Евгений имел в виду что достаточно передать только `@test_passage`, все остальное можно получить используя его

2019-02-24 17:53 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    flash[:notice] = if result.empty?
```
flash[:notice] =
    if result.empty?
      t('.failure')
    else
      t('.success', title: " #{view_context.link_to('Click this link',
        (result[:git_pull_url]).to_s, target: :_blank)}")
      current_user.gists.create(question_id: @test_passage.question.id,
      gist_url: result[:files][:test_guru_question_test][:raw_url],
      user_id: current_user.id)
    end
```
так читабельней и нам не надо создавать гист, если у нас провал

2019-02-24 17:53 UTC, BubuntuClu commented on app/services/distribution_trophies.rb
> +  def user_triohues(deserved_trophy)
думаю тут опечатка в имени метода

2019-02-24 17:53 UTC, BubuntuClu commented on app/services/distribution_trophies.rb
> +      trophies.push(trophy) if option_trophy_level(trophy) ||
тут хорошо использовать тот вариант, что предложил Евгений. таким образом тебе не надо будет условие каждый раз дописывать, если будут новые виды правил

2019-02-24 20:27 UTC, DADUSHKA commented on app/services/distribution_trophies.rb
> +      trophies.push(trophy) if option_trophy_level(trophy) ||
вариант Евгения я не совсем понял, сделал как смог

2019-02-24 20:34 UTC, DADUSHKA commented on app/controllers/test_passages_controller.rb
> +   @trophies_issued = DistributionTrophies.new(@test_passage, @test_passage.user, current_user.test_passages)
Мне нужен текущий test_passage и все testы которые прошел user

2019-02-24 21:46 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +   @trophies_issued = DistributionTrophies.new(@test_passage, @test_passage.user, current_user.test_passages)
Всё так, эту информацию можно получить внутри класса из `@test_passage`.

2019-02-24 22:01 UTC, psylone approved these changes

2019-02-24 22:01 UTC, psylone commented on app/views/test_passages/_trophies.html.erb
> + <%  @trophies_issued.call.each do |p| %>
В обязанности шаблонов входит отображение данных поэтому метод `call` стоит вызывать у объекта `@trophies_issued` в контроллере. У этого объекта стоит сделать метод ридер который вернёт коллекцию полученных бэйджей.

2019-02-24 22:01 UTC, psylone commented on app/services/distribution_trophies.rb
> +  def user_trophues(deserved_trophy)
Будет лучше присваивание бэйджей сделать в контроллере, а здесь сделать метод ридер который вернет массив полученных бэйджей.

2019-02-24 22:01 UTC, psylone commented on app/services/distribution_trophies.rb
> +      trophies.push(trophy) if option_trophy_level(trophy) ||
Мы знаем название правила, оно хранится в объекте `trophy`. С помощью этого значения мы можем вызывать проверки динамически. Для этого нам понадобится метод `send`. С его помощью мы можем сформировать строку с названием метода проверки, а затем вызвать этот метод с помощью `send`:

```ruby
method_name = "option_trophy_#{trophy.precept}"
send(method_name)
```

2019-02-24 22:01 UTC, psylone commented on app/models/test_passage.rb
> +  def timeout?
~Это стоит поместить в метод модели `TestPassage`.~

2019-02-24 22:01 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +   @trophies_issued = DistributionTrophies.new(@test_passage, current_user.test_passages)
На самом деле, эта переменная должна называться `@distribution_trophies` и у неё стоит вызвать метод `call` прямо здесь:

```ruby
@distribution_trophies = DistributionTrophies.new(@test_passage)
@distribution_trophies.call
@distribution_trophies.result # Вернёт массив бэйджей которые нужно выдать пользователю
current_user.trophies.push(*@distribution_trophies.result)
```

2019-02-25 07:37 UTC, merged