Lesson three miss made
DADUSHKA/web_application pull request #6
Opened 2018-10-25 14:44 UTC by DADUSHKA

2018-10-25 15:20 UTC, BubuntuClu requested changes

2018-10-25 15:20 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :test, through: :questions
это что за связь такая?
тебе надо сделать промежуточную таблицу `users_tests`, которая будет хранить в себе информацию о пользователе и тесте, и через эту таблицу и надо доставать тесты

2018-10-25 15:20 UTC, BubuntuClu commented on app/models/user.rb
>      Test.where(level: value).pluck(:title).join("' , '")
этот метод вернет просто все тесты определенного уровня. к текущему пользователю это не будет никак не привязано.
`pluck` тут не надо делать. надо полные AR-объекты вернуть

2018-10-25 15:20 UTC, BubuntuClu commented on db/migrate/20181025125012_add_user_ref_to_questions.rb
> +    add_reference :questions, :user, foreign_key: true
эта связь подразумевает некое авторство вопросов. этого не требуется

2018-10-25 15:20 UTC, BubuntuClu commented on db/schema.rb
> +    t.boolean "correct", default: true
по умолчанию делать ответ правильным нелогично. `false` было правильно

2018-10-25 15:20 UTC, BubuntuClu commented on db/seeds.rb
> +Question.create!(
[тут](https://github.com/DADUSHKA/web_application/pull/5#discussion-diff-227707962R37) оставлял комментарий по  поводу объектов в создании. стоит сделать так

2018-10-25 15:20 UTC, BubuntuClu commented on app/models/test.rb
> +    joins(:category).where(categories: { title: category_name }).pluck(:title)
это правильно, молодец

2018-10-27 18:14 UTC, BubuntuClu commented on app/models/question.rb
> -  belongs_to :test
а зачем удалил привязку к тесту?

2018-10-27 18:14 UTC, BubuntuClu commented on app/models/test.rb
> -  has_many :questions
зачем удалил привязку с вопросами?

2018-10-27 18:14 UTC, BubuntuClu commented on db/migrate/20181027113937_create_users_and_tests.rb
> +      t.belongs_to :user, index: true
индекс автоматически создается, внешний ключ надо руками прописать

2018-10-27 18:14 UTC, BubuntuClu commented on db/seeds.rb
> +    test_id: 1},
а тут почему не стал заменять на объекты?

2018-10-27 18:14 UTC, BubuntuClu commented on db/seeds.rb
> +Answer.create!
это что такое?)

2018-10-27 18:14 UTC, BubuntuClu commented on app/models/category.rb
> +  has_one :tests
это что такое? если это переводить звучит нелогично. если `has_one`, то используется единственное чилсло, так как подразумевается связь с одним объектом

2018-10-27 18:18 UTC, BubuntuClu commented on db/migrate/20181020210012_add_answers_correct_index_default.rb
> +    change_column_default :answers, :correct, from: true, to: false
лучше откатить миграцию и сделать с нуля ее, тогда будет `from: nil, to: false`

2018-10-27 18:18 UTC, BubuntuClu commented on db/migrate/20181021163938_change_column_users.rb
> +    rename_column :users, :status, :login_status
а что за статус у пользователя?

2018-10-27 18:18 UTC, BubuntuClu commented on db/migrate/20181021164012_change_column_tests.rb
> +    rename_column :tests, :status, :finality
а это что за столбец?

2018-10-27 20:27 UTC, DADUSHKA commented on db/migrate/20181021163938_change_column_users.rb
> +    rename_column :users, :status, :login_status
статус admin или просто пользователь

2018-10-27 20:28 UTC, DADUSHKA commented on db/migrate/20181021164012_change_column_tests.rb
> +    rename_column :tests, :status, :finality
тест пройден или нет

2018-10-27 21:45 UTC, psylone approved these changes

2018-10-27 21:45 UTC, psylone commented on db/seeds.rb
> +Answer.delete_all
`[User, Category, Test, Question, Answer].each(&:delete_all)`.

2018-10-27 21:45 UTC, psylone commented on app/models/question.rb
> +  has_one :answer
У вопроса вполне может быть несколько ответов.

2018-10-27 21:45 UTC, psylone commented on app/models/test.rb
> +    joins(:category).where(categories: { title: category_name }).pluck(:title)
Только ещё сортировка нужна.

2018-10-27 21:45 UTC, psylone commented on app/models/user.rb
> +    tests.where(tests: {level: value})
`tests.where(level: value)`.

2018-10-27 21:45 UTC, psylone commented on config/application.rb
> +    config.i18n.available_locales = :ru, :en
Здесь лучше явно присваивать массив: `config.i18n.available_locales = [:ru, :en]`.

2018-10-27 22:04 UTC, merged