Lesson five
DADUSHKA/web_application pull request #7
Opened 2018-10-30 21:24 UTC by DADUSHKA

2018-10-31 09:04 UTC, BubuntuClu requested changes

2018-10-31 09:04 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :user
это назвать надо по другому, допустим, `author`, иначе не понятно чем отличаются `users` и `user`

2018-10-31 09:04 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests
тут я даже не уверен что корректно работает у тебя связь. у тебя две ассоциации с одним именем. назови вторую что-то типа "авторские тесты"

2018-10-31 09:04 UTC, BubuntuClu commented on db/migrate/20181020210012_add_answers_correct_index_default.rb
> +    change_column_default :answers, :correct, from: false, to: true
это зачем делать?
и нельзя менять миграции которые уже в `master` ветке. только через новые миграции

2018-10-31 09:04 UTC, BubuntuClu commented on db/migrate/20181030193952_add_tests_user_id_null_constraint.rb
> +    change_column_null :tests, :user_id, false
а зачем это выносить в отдельную миграцию? можно было описать сразу при добавлении пользователя

2018-10-31 09:06 UTC, BubuntuClu commented
по диаграмме тоже замечания, связь вопрос-ответ не соответствует тому, что у тебя описано в файле `schema.rb`.

2018-11-01 12:15 UTC, psylone approved these changes

2018-11-01 12:36 UTC, merged