Lesson six
DADUSHKA/web_application pull request #8
Opened 2018-11-02 09:53 UTC by DADUSHKA

2018-11-02 12:34 UTC, BubuntuClu requested changes

2018-11-02 12:34 UTC, BubuntuClu commented on app/models/answer.rb
> +  validates :correct, presence: true
это зачем? у тебя дефолтное значение стоит. зачем проверять наличие этого поля?

2018-11-02 12:34 UTC, BubuntuClu commented on app/models/category.rb
> +  default_scope { select(:title).order(created_at: :desc) }
скоуп должен возвращать `ActiveRecord::Relaction`, не надо в него помещать фильтры на выборку столбцов. это делать надо на коллекции, которые вернет тебе скоуп.

2018-11-02 12:34 UTC, BubuntuClu commented on app/models/test.rb
> +    .order(created_at: :desc).pluck(:title) if category_name.present?
так же к вопросу о том что должен возвращать скоуп. и зачем в нем `if`? как он может тут не быть?

2018-11-02 12:34 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :list_of_user_tests_by_difficulty, ->(value) { where(tests: { level: value }) }
это что такое? в названии указан `user`, а как он тут задействован?

2018-11-02 12:34 UTC, BubuntuClu commented on db/migrate/20181102094334_add_index_to_tests_title.rb
> +     add_index :tests, :title, unique: true
индекс должен быть составной на `title, level`

2018-11-02 12:34 UTC, BubuntuClu commented on db/schema.rb
> +    t.boolean "correct", default: true
лучше вернуть как было

2018-11-03 07:44 UTC, BubuntuClu requested changes

2018-11-03 07:44 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :list_of_tests_by_difficulty, ->(value) { where(tests: { level: value }) }
`->(value) { where(level: value) }` ты же ниже точно такие же скоупы делаешь, почему тут синкасис другой стал?
так же ты можешь назвать этот скоуп короче `by_level` и использовать его внутри скоупов уровней теста

2018-11-03 07:44 UTC, BubuntuClu commented on app/models/question.rb
> +  has_many :answers, -> { limit(1..4) }, class_name: "Answer"
у тебя работает это? если ты сделаешь `question.answers`, не будет ли у тебя ошибки?
сделай кастомную валидацию на проверку количества ответов у вопроса

2018-11-04 06:15 UTC, BubuntuClu commented on app/models/question.rb
> +  has_many :answers, -> { limit(1..4) }, class_name: "Answer"
валидации на количество ответов нет

2018-11-04 10:04 UTC, BubuntuClu commented on app/models/question.rb
> +  validate :validate_count_answers
эта валидация должна быть в моделе `answer`, валидация должна быть при попытке сохранить ответ

2018-11-04 10:06 UTC, BubuntuClu commented on app/models/test.rb
> +    .order(created_at: :desc)
сортировки лучше не помещать в скоупы. используй сортировки на резльутате скоупа отдельно, если это требуется

2018-11-04 10:08 UTC, BubuntuClu commented on app/models/user.rb
> +  before_save { self.email = email.downcase }
делай отступы между методами, а  то все сливается в одну кашу

2018-11-04 10:08 UTC, BubuntuClu commented on app/models/user.rb
> +  has_secure_password
логические блоки не надо перемешивать.

если у тебя сначала идет блок валидации, то не надо внутрь вставлять `has_secure_password`

2018-11-04 10:49 UTC, psylone approved these changes

2018-11-04 10:49 UTC, psylone commented on app/models/test.rb
> +    .order(created_at: :desc)
Стоит упростить название скоупа, например, `by_category`. Мы уже находимся в контексте коллекции тестов когда вызываем скоуп, поэтому `Test.test_...` избыточно.

2018-11-04 10:49 UTC, psylone commented on app/models/user.rb
> +  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
Константы принято объявлять в самом начале класса.

2018-11-04 11:04 UTC, merged